services:
  frigate:
    container_name: frigate
    privileged: true
    cap_add:
      - CAP_PERFMON
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:$VERSION
    shm_size: "1024mb"
    devices:
      - $CORAL_USB:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $CONFIG:/config
      - $MEDIA:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "${PORT}:8971"
      - "${FREE_PORT}:5000"
      - "${RTSP_PORT}:8554" # RTSP feeds
      - "${WEB_RTC_TCP_PORT}:8555/tcp" # WebRTC over tcp
      - "${WEB_RTC_UDP_PORT}:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_USER: $FRIGATE_RTSP_USER
      FRIGATE_RTSP_PASSWORD: $FRIGATE_RTSP_PASSWORD