version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    privileged: true
    cap_add:
      - CAP_PERFMON
    shm_size: "512mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/Main Pool/frigate/config:/config
      - /mnt/Main Pool/frigate/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "30971:8971"
      - "30051:5000" # Internal unauthenticated access. Expose carefully.
      - "30554:8554" # RTSP feeds
      - "30555:8555/tcp" # WebRTC over tcp
      - "30555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: $FRIGATE_RTSP_PASSWORD
      CAMS_PASSWORD: $CAMS_PASSWORD