services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIGS}:/app/data/configs
      - ${ICONS}:/app/public/icons
      - ${DATA}:/data
    ports:
      - '${PORT}:7575'