services:
  homelab-hub:
    image: raidowl/homelab-hub:${VERSION:-latest}
    container_name: homelab-hub
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ${DATA}:/data
    restart: unless-stopped
