services:
  mc:
    image: itzg/minecraft-server
    tty: true
    user: "${UID}:${GID}"
    stdin_open: true
    ports:
      - ${PORT}:25565
    environment:
      EULA: "TRUE"
    volumes:
      - ${DATA}:/data