services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - ${PORT}:25565
    environment:
      EULA: "TRUE"
      UID: ${UID}
      GID: ${GID}
    volumes:
      - ${DATA}:/data