version: '3.1'

services:

  mongo:
    image: mongo:8.0.0-rc4-jammy
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongo:/data/db

volumes:
  mongo:
