version: '3.1'

services:

  mongo:
    image: arm64v8/mongo:4.4.18
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongo:/data/db

volumes:
  mongo:
