version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "${PORT}:1883"
      - "9001:9001"
    volumes:
      - ${CONFIG}:/mosquitto/config
      - ${DATA}:/mosquitto/data
      - ${LOG}:/mosquitto/log