version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "9883:1883"
      - "9001:9001"
    volumes:
      - /mnt/Main Pool/mqtt/config:/mosquitto/config
      - /mnt/Main Pool/mqtt/data:/mosquitto/data
      - /mnt/Main Pool/mqtt/log:/mosquitto/log