version: '3.8'

services:
  pihole:
    image: pihole/pihole:2023.05.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "9080:80/tcp"
      - "9443:443/tcp"
    environment:
      TZ: 'Romania/Bucharest'
      WEBPASSWORD: $WEBPASSWORD
    restart: unless-stopped