version: '3.8'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.07.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Bucharest'
      WEBPASSWORD: $PIHOLE_PASSWORD
      FTLCONF_LOCAL_IPV4: $SERVER_IP
    volumes:
      - /mnt/Main Pool/pihole/etc-pihole:/etc/pihole
      - /mnt/Main Pool/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped