version: '3.8'

services:
  pihole:
    image: pihole/pihole:latest
    network_mode:
      'host'
    environment:
      TZ: 'Romania/Bucharest'
      WEBPASSWORD: $WEBPASSWORD
    restart: unless-stopped