version: '3.8'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${CONFIG_PATH}:/config
      - ${TV_SHOWS_PATH}:/tv
      - ${MOVIES_PATH}:/movies
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped