version: '3.8'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${CONFIG}:/config
      - ${TV}:/tv
      - ${MOVIES}:/movies
      - ${AUDIO}:/audio
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped