version: '3.8'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - /mnt/Main Pool/plex:/config
      - /mnt/Main Pool/downloads:/tv
      - /mnt/Main Pool/downloads:/movies
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 32400:32400
      - 31900:1900/udp
      - 35353:5353/udp
      - 38324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    restart: unless-stopped