version: '3.8'

services:
  postgres-db:
    image: postgres
    shm_size: ${SHM_SIZE}
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ${DATA}:/var/lib/postgresql/data