services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG}:/config
      - ${MOVIES}:/movies #optional
      - ${DOWNLOADS}:/downloads #optional
    ports:
      - ${PORT}:7878
    restart: unless-stopped