services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharst
    volumes:
      - ${CONFIG}:/config
      - ${TV}:/tv #optional
      - ${DOWNLOADS}:/downloads #optional
    ports:
      - ${PORT}:8989
    restart: unless-stopped