services:
  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:${TDARR_NODE_VERSION:-latest}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true
    environment:
      - nodeID=${TDARR_NODE_ID:-Node1}
      - serverIP=${TDARR_SERVER_IP}
      - serverPort=${TDARR_SERVER_PORT}
    volumes:
      - ${TDARR_MOVIES_PATH}:/movies
      - ${TDARR_TV_PATH}:/tv
      - ${TDARR_CACHE_PATH}:/tdarr_cache
      - ${TDARR_CONFIG_PATH}:/app/configs
      - ${TDARR_CAMS_PATH}:/cams
    ports:
      - "${TDARR_NODE_PORT:-8267}:8267"