version: '3.8'

services:
  worker:
    image: radusimonica/test_distributor:latest
    command: java -jar /test-distributor/distributedTest.jar --worker --rabbitHost rabbitmq --requestQueue q.request.test --receiveQueue q.receive.result
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_PASS
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    networks:
      - rabbitmq-network

  scaler:
    image: radusimonica/scaler:latest
    command: java -jar scaler.jar --rabbitHost rabbitmq -q q.request.test -p 5000 --dockerHost tcp://192.168.0.150:2375 --dockerServiceName test_worker --threshold 20 --maxConsumers 20
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_PASS
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    driver: overlay
    external: true
    attachable: true

secrets:
  rabbitmq-pass:
    external: true