version: '3.8'

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /mnt/Main Pool/transmission:/config
      - /mnt/Main Pool/downloads:/downloads
    ports:
      - 39091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped