version: '3.8'

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - TZ=Europe/Bucharest
    volumes:
      - ${CONFIG}:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - ${EXT_9091_PORT}:9091
      - ${EXT_51413_PORT_TCP}:51413
      - ${EXT_51414_PORT_UDP}:51413/udp
    restart: unless-stopped