version: '3.8'
services:
    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: koenkk/zigbee2mqtt
        restart: unless-stopped
        volumes:
            - ${DATA}:/app/data
            - /run/udev:/run/udev:ro
        ports:
            - ${PORT}:8080
        environment:
            - TZ=Europe/Bucharest
        devices:
            - ${ZIGBEE}:/dev/ttyACM0